application: query2json
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /
  static_files: markup/index.html
  upload: markup/(.*)

- url: /.+
  script: main.py
